import React from 'react';
import { Composition } from 'remotion';
import manifest from './manifest.json';
import { SCENES } from './scenes/index';

/**
 * One composition per scene, keyed by stable scene ID ("scene-<id>").
 * manifest.json and scenes/index.ts are generated by Rocket Explainer for each render pass.
 */
export const RemotionRoot: React.FC = () => (
  <>
    {manifest.compositions.map((c: any) => (
      <Composition
        key={c.id}
        id={c.id}
        component={(SCENES as Record<string, React.ComponentType<any>>)[c.id]}
        durationInFrames={c.durationInFrames}
        fps={manifest.fps}
        width={manifest.width}
        height={manifest.height}
        defaultProps={c.props}
      />
    ))}
  </>
);
