/** Props every scene component receives. Generated by Rocket Explainer; do not edit. */

export interface WordTiming {
  text: string;
  /** Relative to the start of the scene. */
  startMs: number;
  endMs: number;
  startFrame: number;
  endFrame: number;
}

export interface SceneData {
  /** Stable scene ID. */
  id: string;
  title: string;
  /** What the narrator says during this scene (audio is added after rendering). */
  narration: string;
  /** What the scene should show. */
  visuals: string;
  /** Style elements this scene exercises, e.g. opening, transition, text-popups, boxes, diagram, camera. */
  elements: string[];
  durationMs: number;
  words: WordTiming[];
}

/** The style's design tokens (the YAML block of its DESIGN.md): colors, typography, motion, camera, ... */
export type StyleTokens = Record<string, any> & {
  colors?: Record<string, string>;
  typography?: Record<string, { family?: string; weight?: number; [k: string]: unknown }>;
};

export interface SceneProps {
  scene: SceneData;
  style: StyleTokens;
}
